server:
  port: 8105

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8085/eureka-server/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false
      routes:
        - id: my-service
          uri: lb://my-service
          predicates:
            - Path=/service/**

