server:
  port: 8101
spring:
  application:
    name: my-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8085/eureka-server/eureka
  instance:
    prefer-ip-address: true
